security:
  oauth2:
    client:
      clientId: 233668646673605
      clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
      accessTokenUri: http://localhost:8090/oauth/access_token
      userAuthorizationUri: http://localhost:8090/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://localhost:8090/me
  user:
    name: root
    password: 123456
spring:
  application:
    name: kafka_api
server:
  port: 8090

#application.name=kafka_api
#server.port=8090
#server.tomcat.uri-encoding=UTF-8
#
#
#spring.datasource.platform=h2
#
#security.user.name=root
#security.user.password=123456
#security.oauth2.client.client-id=app10001
#security.oauth2.client.client-secret=32269ae63a25306bb46a03d6f38bd2b7
#security.oauth2.authorization.checkTokenAccess=isAuthenticated()
#
#logging.level.org.springframework.security=DEBUG
